<select name="category" id="category" class="form-control">
                                        <option value="Art">Art</option>
                                        <option value="2">Everything else</option>
                                        <option value="2.12">Antiques</option>
                                        <option value="2">Baby</option>
                                        <option value="1">Books & Magazines</option>
                                        <option value="Business & Industrial">Business & Industrial</option>
                                        <option value="Cameras & Photo">Cameras & Photo</option>
                                        <option value="Cell Phones & Accessories">Cell Phones & Accessories</option>
                                        <option value="Clothing, Shoes & Accessories">Clothing, Shoes & Accessories</option>
                                        <option value="Coins & Paper Money">Coins & Paper Money</option>
                                        <option value="Collectibles">Collectibles</option>
                                        <option value="Computers/Tablets & Networking">Computers/Tablets & Networking</option>
                                        <option value="Consumer Electronics">Consumer Electronics</option>
                                        <option value="Crafts">Crafts</option>
                                        <option value="Dolls & Bears">Dolls & Bears</option>
                                        <option value="eBay Motors">eBay Motors</option>
                                        <option value="Entertainment Memorabilia">Entertainment Memorabilia</option>
                                        <option value="Health & Beauty">Health & Beauty</option>
                                        <option value="Home & Garden">Home & Garden</option>
                                        <option value="Jewelry & Watches">Jewelry & Watches</option>
                                        <option value="Movies & TV">Movies & TV</option>
                                        <option value="Music">Music</option>
                                        <option value="Musical Instruments & Gear">Musical Instruments & Gear</option>
                                        <option value="Pet Supplies">Pet Supplies</option>
                                        <option value="Pottery & Glass">Pottery & Glass</option>
                                        <option value="Specialty Services">Specialty Services</option>
                                        <option value="Sporting Goods">Sporting Goods</option>
                                        <option value="Sports Mem, Cards & Fan Shop">Sports Mem, Cards & Fan Shop</option>
                                        <option value="5.1">Stamps</option>
                                        <option value="Toys & Hobbies">Toys & Hobbies</option>
                                        <option value="Video Games & Consoles">Video Games & Consoles</option>
                                    </select>
